### ISSUE TITLE
[question]，An error occurred while testing function mesh

### ISSUE THREAD

**Issue by xuesongxs** [streamnative/function-mesh#177]
![image](https://user-images.githubusercontent.com/54351417/119798586-dc833b00-bf0d-11eb-92a4-f5ef549f9f5c.png)

**Comment by nlu90** [comment]
@xuesongxs 

Thanks for reporting this issue. This issue could be avoided by using `kubectl create` instead of `kubectl apply` when installing the CRDs.

We will make a new release and fix this issue this week.

**Comment by freeznet** [comment]
This issue has been solved by https://github.com/streamnative/function-mesh/pull/150, we will push a new release this week. Before that, please take @nlu90 's comment, using `kubectl create -f crd.yml` directly.
