### ISSUE TITLE
compile mesh-worker-service failed

### ISSUE THREAD

**Issue by xuesongxs** [streamnative/function-mesh#191]
![image](https://user-images.githubusercontent.com/54351417/120735755-bf59f800-c51d-11eb-9889-5b75df7d18e0.png)

cmd: mvn install

**Comment by tuteng** [comment]
You need to generate crd model first for the mesh worker service https://github.com/streamnative/function-mesh/tree/master/mesh-worker-service#more-tools, or run this script https://github.com/streamnative/function-mesh/blob/master/mesh-worker-service/tool/generate-crd.sh @xuesongxs
