### ISSUE TITLE
pulsar-admin sink command not working as expected 

### ISSUE THREAD

**Issue by rockybean** [streamnative/function-mesh#218]
I try to create a sink connector with the following command.

```
bin/pulsar-admin sinks create --name sqs-sink-28rc3 --sink-type sqs --inputs persistent://public/default/random-data-topic --sink-config '{"awsCredentialPluginName":"","awsCredentialPluginParam":"{\"accessKey\": \"\",\"secretKey\": \"\"}","awsEndpoint":"https://sqs.cn-north-1.amazonaws.com.cn","awsRegion":"cn-north-1","queueName":"sqs-connector-test"}' --classname org.apache.pulsar.ecosystem.io.sqs.SQSSink 
```

The result of command is `Created Successfully!`. But when I check in k8s, no relative pod starts. And I find function mesh operator pod is keeping restart with following logs.

![image](https://user-images.githubusercontent.com/1431033/123072180-e71aec80-d447-11eb-87fe-75860374a815.png)

After some investigation, it seems like that `--auto-ack true` is required here.

Maybe we can make an enhancement here to set a default value to auto-ack.

**Comment by freeznet** [comment]
@rockybean cloud you please provide more details about this issue? like version info for both Pulsar and function mesh, thanks.
