### ISSUE TITLE
Support running functions/connectors with a custom service account

### ISSUE THREAD

**Issue by fantapsody** [streamnative/function-mesh#221]
- [x] expose the `serviceAccountName` in CRDs
- [x] allow to configure the `serviceAccountName` used to run functions/connectors in the mesh-worker-service

**Comment by Huanli-Meng** [comment]
@fantapsody it seems the code and doc are added to release v0.1.6. Should we close this issue? Thanks

**Comment by fantapsody** [comment]
> @fantapsody it seems the code and doc are added to release v0.1.6. Should we close this issue? Thanks

There is still a remaining task in this issue, so please wait a little longer.

**Comment by Huanli-Meng** [comment]
> > @fantapsody it seems the code and doc are added to release v0.1.6. Should we close this issue? Thanks
> 
> There is still a remaining task in this issue, so please wait a little longer.

OK

**Comment by Huanli-Meng** [comment]
Confirmed with Rui, all tasks have been done. Doc will be tracked in a new issue.
