### ISSUE TITLE
Support upload and download package

### ISSUE THREAD

**Issue by tuteng** [streamnative/function-mesh#227]
https://github.com/streamnative/function-mesh/blob/master/mesh-worker-service/src/main/java/io/functionmesh/compute/rest/api/MeshComponentImpl.java#L361

https://github.com/streamnative/function-mesh/blob/master/mesh-worker-service/src/main/java/io/functionmesh/compute/rest/api/MeshComponentImpl.java#L369

**Comment by tuteng** [comment]
Update: I think as an open-source project, the function mesh worker would need to support submitting functions/connectors with NAR packages

**Comment by freeznet** [comment]
https://github.com/streamnative/function-mesh/issues/232
use the default directory if user not provided for download
