### ISSUE TITLE
Observed a panic: "invalid memory address or nil pointer dereference" 部署function遇到这个问题 

### ISSUE THREAD

**Issue by dhwell** [streamnative/function-mesh#236]
E0722 13:43:10.531369       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 407 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x15631e0, 0x24903c0)
	k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:48 +0x82
panic(0x15631e0, 0x24903c0)
	runtime/panic.go:679 +0x1b2
github.com/streamnative/function-mesh/controllers/spec.convertFunctionDetails(0xc00040ec00, 0xd4a2f12dba4b77ef)
	github.com/streamnative/function-mesh@/controllers/spec/utils.go:44 +0x307
github.com/streamnative/function-mesh/controllers/spec.generateFunctionDetailsInJSON(0xc00040ec00, 0xc0000c3298, 0xc000879390)
	github.com/streamnative/function-mesh@/controllers/spec/function.go:127 +0x2f
github.com/streamnative/function-mesh/controllers/spec.makeFunctionCommand(0xc00040ec00, 0x40c618, 0x50, 0x14fc540)
	github.com/streamnative/function-mesh@/controllers/spec/function.go:106 +0xb5
github.com/streamnative/function-mesh/controllers/spec.MakeFunctionContainer(0xc00040ec00, 0xc000408100)
	github.com/streamnative/function-mesh@/controllers/spec/function.go:81 +0x99
github.com/streamnative/function-mesh/controllers/spec.MakeFunctionStatefulSet(0xc00040ec00, 0xc0004cc8a0)
	github.com/streamnative/function-mesh@/controllers/spec/function.go:47 +0x61
github.com/streamnative/function-mesh/controllers.(*FunctionReconciler).ApplyFunctionStatefulSet(0xc000697f80, 0x1963540, 0xc0000460c8, 0xc0003dd9b0, 0x8, 0xc0009510e0, 0x14, 0xc00040ec00, 0x0, 0x0)
	github.com/streamnative/function-mesh@/controllers/function.go:94 +0x226
github.com/streamnative/function-mesh/controllers.(*FunctionReconciler).Reconcile(0xc000697f80, 0xc0003dd9b0, 0x8, 0xc0009510e0, 0x14, 0xc0003b6da0, 0xc0001ca518, 0x1938560, 0xc0001ca510)
	github.com/streamnative/function-mesh@/controllers/function_controller.go:88 +0x3f0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000103050, 0x15b9d40, 0xc0003b6c00, 0x2493d00)
	sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235 +0x27d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000103050, 0x0)
	sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000103050)
	sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0008ec3a0)
	k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0008ec3a0, 0x1929000, 0xc00076a240, 0x1, 0xc00040c420)
	k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0008ec3a0, 0x3b9aca00, 0x0, 0x1, 0xc00040c420)
	k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0xaa
k8s.io/apimachinery/pkg/util/wait.Until(0xc0008ec3a0, 0x3b9aca00, 0xc00040c420)
	k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:170 +0x431
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1401417]

`
apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: java-function-sample
  namespace: fast-dev
spec:
  image: ***function:latest
  className: ***Function
  forwardSourceMessageProperty: true
  MaxPendingAsyncRequests: 1000
  replicas: 1
  maxReplicas: 5
  logTopic: persistent://public/default/logging-function-logs
  input:
    topics:
    - persistent://public/default/java-function-input-topic
    typeClassName: java.lang.String
  output:
    topic: persistent://public/default/java-function-output-topic
    typeClassName: java.lang.String
  pulsar:
    pulsarConfig: "pulsar-config"
  java:
    jar: /pulsar/custom.jar
    jarLocation: ""
  clusterName: standalone
`

**Comment by freeznet** [comment]
https://github.com/streamnative/function-mesh/pull/234 fixes this issue

**Comment by dhwell** [comment]
> 
> 
> @dhwell thanks, this is a known issue and #234 fixes this issue.

@freeznet 这个错误和已修复的这个错误不一样  这个错误是在创建function时候产生的 错误仍然没有修复

**Comment by dhwell** [comment]
@freeznet The docker image hasnot been updated.  still streamnative/function-mesh:v0.1.6-rc3

**Comment by freeznet** [comment]
@dhwell yes, v0.1.6-rc3 has not contained the fix yet, we will push a new release at end of this month, stay tuned.

**Comment by dhwell** [comment]
> 
> 
> @dhwell yes, v0.1.6-rc3 has not contained the fix yet, we will push a new release at end of this month, stay tuned.

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1405a12]

goroutine 381 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1563220, 0x24963c0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/streamnative/function-mesh/controllers.(*FunctionReconciler).ObserveFunctionStatefulSet(0xc00053c180, 0x19639e0, 0xc0000640c0, 0xc0005812d0, 0x8, 0xc0006bc320, 0x14, 0xc0008e4000, 0xc0008e4000, 0x0)
	/workspace/controllers/function.go:66 +0x2e2
github.com/streamnative/function-mesh/controllers.(*FunctionReconciler).Reconcile(0xc00053c180, 0xc0005812d0, 0x8, 0xc0006bc320, 0x14, 0xc000586920, 0xc000100758, 0x1938a00, 0xc000100750)
	/workspace/controllers/function_controller.go:69 +0x1ff
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001aa7e0, 0x15b9d80, 0xc00082a1c0, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235 +0x27d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001aa7e0, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001aa7e0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0006a8030)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006a8030, 0x19294a0, 0xc0006c8060, 0x1, 0xc0003f83c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006a8030, 0x3b9aca00, 0x0, 0x1, 0xc0003f83c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0xaa
k8s.io/apimachinery/pkg/util/wait.Until(0xc0006a8030, 0x3b9aca00, 0xc0003f83c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:170 +0x431

重新构建镜像后又有新的bug

java function：

shardId=0
Invalid maximum heap size: -Xmx0
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
