### ISSUE TITLE
github.com/streamnative/function-mesh/controllers.(*FunctionReconciler).ObserveFunctionStatefulSet

### ISSUE THREAD

**Issue by dhwell** [streamnative/function-mesh#237]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1405a12]

goroutine 435 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1563220, 0x24963c0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/streamnative/function-mesh/controllers.(*FunctionReconciler).ObserveFunctionStatefulSet(0xc00044ca50, 0x19639e0, 0xc0000640c0, 0xc00091a650, 0x8, 0xc000346a80, 0x14, 0xc0001d6800, 0xc0001d6800, 0x0)
	/workspace/controllers/function.go:66 +0x2e2
github.com/streamnative/function-mesh/controllers.(*FunctionReconciler).Reconcile(0xc00044ca50, 0xc00091a650, 0x8, 0xc000346a80, 0x14, 0xc000335bc0, 0xc00052a1b8, 0x1938a00, 0xc00052a1b0)
	/workspace/controllers/function_controller.go:69 +0x1ff
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00052b4d0, 0x15b9d80, 0xc00083d360, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235 +0x27d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00052b4d0, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00052b4d0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00033d0f0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00033d0f0, 0x19294a0, 0xc0002f4930, 0x1, 0xc0005500c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00033d0f0, 0x3b9aca00, 0x0, 0x1, 0xc0005500c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0xaa
k8s.io/apimachinery/pkg/util/wait.Until(0xc00033d0f0, 0x3b9aca00, 0xc0005500c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:170 +0x431

**Comment by freeznet** [comment]
These kinds of faults are mostly like caused by invalid CRD submitted, will be solved with #235.
