### ISSUE TITLE
Current Release 0.16 does not work with recent kind image

### ISSUE THREAD

**Issue by tspannhw** [streamnative/function-mesh#252]
DEBUG: docker/images.go:70] Pulling image: kindest/node:v1.17.2 ...
 ✓ Ensuring node image (kindest/node:v1.17.2) 🖼
 ✓ Preparing nodes 📦 📦 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
 ✓ Joining worker nodes 🚜
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a nice day! 👋
check Kubernetes failed, error: WARNING: version difference between client (1.21) and server (1.17) exceeds the supported minor version skew of +/-1

**Comment by freeznet** [comment]
we have tested the kind image v1.17.17 and it works fine. according to the log, it seems related to the version of the client in your own enviroment.
