### ISSUE TITLE
Compatible with pulsar-all based on ubuntu 20.04

### ISSUE THREAD

**Issue by timmyyuan** [streamnative/function-mesh#270]
Due to the base image of pulsar-all comes from ubuntu 20.04 (https://github.com/apache/pulsar/pull/11026), some images may be incompatible with the new pulsar-all image. For example,  the build process of `pulsar-functions-python-runner` image will be broken because it requires `python3.7`, `python3.7-dev` and `libreadline-gplv2-dev`, which are not available on ubuntu 20.04.

**Comment by freeznet** [comment]
fixed in https://github.com/streamnative/function-mesh/pull/268/commits/fb597d62ab3ebaae1aa140518a277f0d2092b54b and https://github.com/streamnative/function-mesh/pull/268/commits/116e3c9e3944b80cc13b6a3a256afb65f1ad905b
