### ISSUE TITLE
Memory Limits

### ISSUE THREAD

**Issue by polyzos** [streamnative/function-mesh#275]
When running a function or connector seems like the minimum memory setting should be 1GB.
Is there a particular reason for this? This makes it hard for local dev when you have multiple functions you need to test and also requires more resource allocation than needed when a function performs just simple operations like forwarding messages or a simple filtering.

**Comment by freeznet** [comment]
Hi @polyzos, sorry for the late reply, have tried to set the memory to less than 1GB with the `resources` field in CRD?

**Comment by polyzos** [comment]
Hi @freeznet .. It's been a long time so i need to try and reproduce it, but as i remember when i was trying to set the memory to less than 1GB it was failing the pods
https://github.com/streamnative/streamnative-academy/blob/master/microservices-webinars/deployment/mesh.yaml

**Comment by freeznet** [comment]
@polyzos thanks for the context, I will try to reproduce the issue first.

**Comment by jiangpengcheng** [comment]
I did some benchmarks recently with memory set to 0.5g for requests and limits(and with CPU equals to 500m),  pods running well, and below is a sample result:

![image](https://user-images.githubusercontent.com/1858477/224220505-4eb89189-23cd-4759-9d63-110d2559e657.png)


so I think there should be no such limits, or it may be already resolved

**Comment by jiangpengcheng** [comment]
closing as not reproduced
