### ISSUE TITLE
use `kubectl wait` in actions 

### ISSUE THREAD

**Issue by freeznet** [streamnative/function-mesh#314]
ref: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#wait

**Comment by hantmac** [comment]
This function need to implement a `kubectl plugin` for `function-mesh` like [this project](https://github.com/openkruise/kruise-tools), I would like to do this task.

**Comment by freeznet** [comment]
thanks for the advice, this task is targeting to improve the github actions in function mesh repo. Currently, we use sleep to wait for k8s resources, and we should change the scripts to use `kubectl wait` for better experience. 
Meanwhile, the plugin idea should be a good way to manage and use function mesh and provide a CLI tool to the user, and we can create a new issue for this task.
