### ISSUE TITLE
doc: beginner findings

### ISSUE THREAD

**Issue by hpvd** [streamnative/function-mesh#320]
When going through the doc, there are a few things not perfectly clear (to a function mesh beginner)

1)  Which set of functions does/should a function mesh contain?
a) all functions used in the cluster or
b) all functions belonging to one single "(big) task"

if b) there could be several meshes be used/exist in one cluster?

2) on which level will kubernetes loadscaling be used?
per complete mesh or per function?

3) Are there already possibilities to deal with different versions of functions?

**Comment by freeznet** [comment]
@hpvd thanks for asking.
1. should be b), a mesh (set of functions) is aims to solve complex data processing which is hard to be managed with Pulsar Functions Worker. And yes, a cluster can have multiple meshes to do different jobs.
2. HPA is been used on function level, so each function/connector can have their own HPA to do the autoscaling. Mesh is just a collection of functions and connectors, so you can set different HPA rules to each functions in a Mesh.
3. I am not very sure about "different versions" here. can you please provide more info here?

**Comment by hpvd** [comment]
many thanks for your answers! That helps a lot to complete the picture of function mesh.

regarding 3)
was thinking about things that make it easy/clear/fault-resistent to work with different versions of the same function in a mesh
like starting with function A v0.1, optimizing this function/its code and give it a new version number function A v0.2
then we want to use this latest version v0.2,
a day later we notice some misbehaving and wanted to go back to v0.1 to check if this was also there with this older version...

**Comment by freeznet** [comment]
@hpvd sure you can have different versions of the same function with function mesh.

- you can build different versions with different docker image
- you can upload the different versions with [Pulsar Package Management Service](https://pulsar.apache.org/docs/en/admin-api-packages/)

and you can have the rollback with function mesh to revert to previous settings or configs of the function or connector.

**Comment by freeznet** [comment]
not active for 3 weeks, close it, please feel free to re-open it with followup questions.
