### ISSUE TITLE
Support more controller manager params for helm charts

### ISSUE THREAD

**Issue by hantmac** [streamnative/function-mesh#332]
Because of [this pr](https://github.com/streamnative/function-mesh/pull/329), we should support more controller manager params for helm charts.

**Comment by hantmac** [comment]
@freeznet I found that we can just use the default value, no need to add it to helm charts. What do you think?

<img width="636" alt="image" src="https://user-images.githubusercontent.com/7600925/157830077-670ec110-574b-43bf-a12f-8d63d802a1a9.png">

**Comment by freeznet** [comment]
@hantmac thanks, from my understanding, when user using function-mesh, they usally uses helm charts or OLM to install the operator into the k8s cluster. When using helm charts, user needs to change the `values.yaml` to make some customizations, and the manager's configs should be configurable from `values`. So I suggest we add the configurable fields to the `values`, and generate the `args` based on the `values`.

**Comment by hantmac** [comment]
> @hantmac thanks, from my understanding, when user using function-mesh, they usally uses helm charts or OLM to install the operator into the k8s cluster. When using helm charts, user needs to change the `values.yaml` to make some customizations, and the manager's configs should be configurable from `values`. So I suggest we add the configurable fields to the `values`, and generate the `args` based on the `values`.

Make sense. I will add the configurable fields to the `values`.
