### ISSUE TITLE
create and publish a pulsar-admin ready-to-use toolkit image

### ISSUE THREAD

**Issue by jiangpengcheng** [streamnative/function-mesh#399]

**Comment by jiangpengcheng** [comment]
I tested with https://github.com/streamnative/pulsarctl in the alpine base image and it works well, I think we can use it

@freeznet any opinion?

**Comment by freeznet** [comment]
@jiangpengcheng lgtm

**Comment by jiangpengcheng** [comment]
ok, then about pushing images to DockerHub, I see images under StreamNative are published automatically, do you know how to add a new docker image in the automatic procedure?

![image](https://user-images.githubusercontent.com/1858477/174749930-94996c81-e39b-405d-aaf4-af3d6264b05a.png)

**Comment by freeznet** [comment]
@jiangpengcheng you can check https://github.com/streamnative/streamnative-ci, and maybe we can add the image to pulsarctl repo and make the image release with pulsarctl.

**Comment by jiangpengcheng** [comment]
@freeznet 
created a pr on: https://github.com/streamnative/streamnative-ci/pull/2094, is this in the right format? I see the build step was skipped
