### ISSUE TITLE
when TLSSecret is provided, all tls related parameters are required

### ISSUE THREAD

**Issue by jiangpengcheng** [streamnative/function-mesh#412]
when `TLSSecret` is specified, then the below parameters are all required in that secret:

```
use_tls:
tls_allow_insecure:
hostname_verification_enabled:
tls_trust_cert_path:
```

which doesn't look good to users

**Comment by jiangpengcheng** [comment]
another thing is that `tls_trust_cert_path` is a file, is it better to use a secret to mount it?

otherwise, since our providing runner images doesn't have that file, users need to build a new docker image to include the `tls_trust_cert_path`

**Comment by jiangpengcheng** [comment]
@streamnative/serverless any opinion?

**Comment by freeznet** [comment]
thanks @jiangpengcheng for this issue, I think there are two things that need to solve here:

- the controller doesn't load the secrets referenced by the resource, which may lead to the issue of incomplete function command when the secret does not contain all info. One possible solution is to read the secret first, then construct the commands based on the secret keys. 
- For the cert path issue, certs can be mounted separately with `.spec.pod.volumeMounts` and `.spec.volumes`, then use `tls_trust_cert_path` in tls secret. If we are not changing this part, we should add some doc to let the user know how to use this feature, like a use-case section on the function-mesh website.

**Comment by jiangpengcheng** [comment]
I think it's better to add a field for `tls_trust_cert_path` explicitly to generate volume&volume mount since the init container for downloading packages/functions may also require the `tls_trust_cert_path`
