### ISSUE TITLE
support define log level

### ISSUE THREAD

**Issue by freeznet** [streamnative/function-mesh#413]
Currently, if the user wants to output more logging level logs other than `INFO`, it should provide the log settings for different pulsar function runtimes, like for java, it should provide a replacement of `kubernetes_instance_log4j2.xml` config file.

It will be useful if function-mesh provides a runtime level setting `logLevel` and let the controller update the log level of each function instance.

**Comment by tpiperatgod** [comment]
# proposal

## Logging module in Runtimes

### Java

library: log4j https://logging.apache.org/log4j/2.x/manual/configuration.html

supported logging levels:

- off
- trace
- debug
- info
- warn
- error
- fatal
- all

### Python

library: logger https://docs.python.org/3/howto/logging.html

supported logging levels:

- debug
- info
- warning
- error
- critical

### Golang

library: logrus https://github.com/sirupsen/logrus

supported logging levels:

- panic
- fatal
- error
- warning
- info
- debug
- trace

## Implementation in FunctionMesh

I propose to place the log level configuration entry under the `Runtime` field.

```go
type FunctionSpec struct {
    ...
    Runtime `json:",inline"`
    ...
}
```

It will look like:

### Java

```yaml
apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: function-sample
  namespace: default
spec:
  java:
    logLevel: "debug"
```

### Python

```yaml
apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: function-sample
  namespace: default
spec:
  python:
    logLevel: "debug"
```

### Golang

```yaml
apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: function-sample
  namespace: default
spec:
  golang:
    logLevel: "debug"
```

## Implementation of logging level settings in Runtimes

### Java

- Option 1

  Mount the configmap volume associated with the `kubernetes_instance_log4j.xml` file for Function statefulsets via FunctionMesh, and then we can update `kubernetes_instance_log4j.xml` based on the Function Spec.

### Python

- Option 1

  Add the `--logging_level` argument to `python_instance_main.py` to pass in the logging level, and add the following handle logic to `log.py` to set the logging level for each handlers.

  ```python
  def init_logger(level, logfile, logging_config_file):
      global Log
      # get log file location for function instance
      os.environ['LOG_FILE'] = logfile
      logging.config.fileConfig(logging_config_file)
      Log = logging.getLogger()
      Log.setLevel(level)
      
      # set logging level for each handler
      for h in Log.handlers:
          h.setLevel(level)
  ```

- Option 2

  Use only `/pulsar/conf/functions-logging/console_logging_config.ini` for logging configuration；Mount the configmap volume associated with the `console_logging_config.ini` file for Function statefulsets via FunctionMesh, and then we can update `console_logging_config.ini` based on the Function Spec; Remove the following handle logic from `log.py`:

  ```python
  def init_logger(level, logfile, logging_config_file):
      global Log
      # get log file location for function instance
      os.environ['LOG_FILE'] = logfile
      logging.config.fileConfig(logging_config_file)
      Log = logging.getLogger()
      # Log.setLevel(level) # remove this line
  ```

### Go

- Option 1

  Pass in the logging level via environment variable, such as setting `LOGGING_LEVEL`, then add parsing of the `LOGGING_LEVEL` environment variable in `log.go`, , and finally set the logging level.

  ```go
  const (
  	logLevel             = "LOGGING_LEVEL"
    defaultLogLevel      = log.InfoLevel
  )
  
  func init() {
  	if levelStr := os.Getenv(logLevel); levelStr != "" {
  		if level, err := log.ParseLevel(levelStr); err == nil {
  			log.SetLevel(level)
  		}
  	}
  	log.SetLevel(defaultLogLevel)
  	log.AddHook(&contextHook{})
  	log.SetFormatter(&TextFormatter{})
  }
  ```

PTAL when you have time @streamnative/serverless

**Comment by freeznet** [comment]
Some questions here:

- do we need to unify the options of the log level for all languages? 
- https://github.com/apache/pulsar/pull/16939 is in Pulsar 2.11, so the log level support for python and golang should only applied to 2.11+, right?

**Comment by tpiperatgod** [comment]
> * do we need to unify the options of the log level for all languages?

I have adjusted the Spec as shown below:

```yaml
spec:
  java:
    log:
      level: "debug" # Log level
      logConfig: "config-file" # ConfigMap name
```

And the following is the design of the log level options:

```go
const (
	// Off indicates no logging and is only available for the Java runtime
	Off LogLevel = "off"
	// Trace indicates the detailed debugging purposes, available for Python, Go and Java runtime
	Trace LogLevel = "trace"
	// Debug indicates the debugging purposes, available for Python, Go and Java runtime
	Debug LogLevel = "debug"
	// Info indicates the normal purposes, available for Python, Go and Java runtime
	Info LogLevel = "info"
	// Warn indicates the unexpected purposes, available for Python, Go and Java runtime
	Warn LogLevel = "warn"
	// Error indicates the errors have occurred, available for Python, Go and Java runtime
	Error LogLevel = "error"
	// Fatal indicates the server is unusable, available for Python, Go and Java runtime
	Fatal LogLevel = "fatal"
	// All indicates that all logs are logged and is only available for the Java runtime
	All LogLevel = "all"
	// Panic indicates the server is panic and is only available for the Go runtime
	Panic LogLevel = "panic"
)
```

> * [[feature][function] add the ability to customize logging level for Go & Python functions apache/pulsar#16939](https://github.com/apache/pulsar/pull/16939) is in Pulsar 2.11, so the log level support for python and golang should only applied to Pulsar 2.11+, correct?

Yes, I was just about to discuss this... 

I have some plans:
- For the 2.11+ function images, we can apply logging levels and logging config directly
- For the 2.11- function images, we need to hack the Golang or Python function code during controller processing before applying the logging level and logging config**

or do we have any guidelines to follow?
