### ISSUE TITLE
migrate `ClusterRole` to `rbac.authorization.k8s.io/v1`

### ISSUE THREAD

**Issue by freeznet** [streamnative/function-mesh#419]
ref: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122

RBAC resources

The rbac.authorization.k8s.io/v1beta1 API version of ClusterRole, ClusterRoleBinding, Role, and RoleBinding is no longer served as of v1.22.

Migrate manifests and API clients to use the rbac.authorization.k8s.io/v1 API version, available since v1.8.
All existing persisted objects are accessible via the new APIs
No notable changes

**Comment by freeznet** [comment]
```
Value function-mesh.v0.3.0: this bundle is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for ClusterRole: (["function-mesh-metrics-reader"])
```
https://github.com/k8s-operatorhub/community-operators/pull/1419#issuecomment-1174732477

**Comment by hpvd** [comment]
Maintenance support of the for function mesh needed compatible version of Kubernetes v1.21 ended on 28 Jun 2022

Maintenance support for v1.22 will end in 2 weeks (28 Oct 2022)

latest version of Kubernetes is 1.25 was released on 23 Aug 2022

https://endoflife.date/kubernetes
