### ISSUE TITLE
FunctionMesh Operator stateful set image update problem

### ISSUE THREAD

**Issue by armangurkan** [streamnative/function-mesh#421]
Hello there, 

We are using function-mesh operator version v0.2.0.
We use argocd for our deployment of functions.

When we deploy new version of our functions, function mesh CRD gets updated with the latest image we define.  But the statefulset of the functions and as expected pods do not get that change.  The function mesh CRD and the resources it creates stays out of sync.

I would really appreciate any help or guidance on the problem.

**Comment by tpiperatgod** [comment]
Does the "deploy new version of our functions" mean the change in image tags?

**Comment by armangurkan** [comment]
Sorry about the lack of elaboration on that aspect, what I mean is the image parameter on the function it-self, that is defined under the function-mesh manifest.  So, I see that it is updated when I update the function-mesh (in the CRD), it does not trickle down to the k8s resources.  If I delete the crd and let it be re-created by argocd, everthing is re-instantiated as it is supposed to be.

**Comment by tpiperatgod** [comment]
Thanks, I have verified that this is indeed a bug.
