### ISSUE TITLE
Reconcile functions in `FunctionMesh` correctly

### ISSUE THREAD

**Issue by tpiperatgod** [streamnative/function-mesh#426]
for now the `FunctionMesh` does not properly reconcile the functions in `.spec.functions[*]`.

case:
1. create a `FunctionMesh` that contains three functions `function-1-a`, `function-2-a`, `function-3-a`
2. update the name of the function `function-1-a`: `.spec.functions[<function-1-a.index>].name` => `function-1-b`
3. find that the `function-1-b` has been created while `function-1-a` is still alive 

expect：
In step 3 above, `function-1-a` needs to be removed to keep the function configuration in `FunctionMesh` consistent with the actual state

**Comment by tpiperatgod** [comment]
I suggest changing the reconciliation process for FunctionMesh to look like this.

> The main change is to mark (set the "orphaned" annotation or something like this) and delete those orphan subcomponents
>
> For FunctionMesh "orphan subcomponent" refers to subcomponent that is included in an existing FunctionMesh but is not in the current reconcile process
![functionmesh](https://user-images.githubusercontent.com/2360535/179143912-89e5546a-4eef-4ec8-9559-131aaeee7f81.png)

Also, the reconciliation process for subcomponents (Function/Sink/Source) will be changed.

> The "IsOrphaned" is added to the process.
>
> A subcomponent is considered orphaned if it meets any of the following conditions.

condition 1:

    1. has `metadata.ownerReferences`
    2. owner no longer exist or owner does not contain the resource anymore

condition 2:

    1. has `metadata.ownerReferences`
    2. has `orphaned` annotation

![subcomponents](https://user-images.githubusercontent.com/2360535/179144755-dfd50990-1e92-4b2b-8c5d-d307b0558d40.png)

**Comment by jiangpengcheng** [comment]
looks great!

**Comment by tpiperatgod** [comment]
ok, I'll solve this issue based on the proposal above, feel free to give me any advice.

**Comment by nlu90** [comment]
LGTM!

 Also, the manifest update may trigger a follow-up update of resources, are you also going to solve it?

**Comment by tpiperatgod** [comment]
> LGTM!
> 
> Also, the manifest update may trigger a follow-up update of resources, are you also going to solve it?

Could you show me an explicit case?

**Comment by nlu90** [comment]
> > LGTM!
> > Also, the manifest update may trigger a follow-up update of resources, are you also going to solve it?
> 
> Could you show me an explicit case?

The function mesh also includes sources and sinks, they will also need to follow the new reconciliation process.

**Comment by tpiperatgod** [comment]
> The function mesh also includes sources and sinks, they will also need to follow the new reconciliation process.

yes, the new reconciliation process will cover all of these resources.
