### ISSUE TITLE
Admission Webhook should check and limit the submitted CR name 

### ISSUE THREAD

**Issue by nlu90** [streamnative/function-mesh#436]
Resources like statefuleset, and service has name length restrictions, we should notify the user as early as possible if the function/source/sink name length will cause failures in creating these underlying resource objects

An example: https://github.com/streamnative/cloud-support-tickets/issues/119

**Comment by tpiperatgod** [comment]
function
- sts name: <function name>-function, 9 fixed chars
- svc name: <function name>-function-headless, 18 fixed chars
- pod label controller-revision-hash: <function name>-function-<10 * chars>, 20 fixed chars
- hpa name: <function name>-function, 9 fixed chars
fixed chars length: 20, length of <function name>: 1~43

sink
- sts name: <sink name>-sink, 5 fixed chars
- svc name: <sink name>-sink-headless, 14 fixed chars
- pod label controller-revision-hash: <sink name>-sink-<10 * chars>, 16 fixed chars
- hpa name: <sink name>-sink, 5 fixed chars
fixed chars length: 16, length of <sink name>: 1~47

source
- sts name: <source name>-source, 7 fixed chars
- svc name: <source name>-source-headless, 16 fixed chars
- pod label controller-revision-hash: <source name>-source-<10 * chars>, 18 fixed chars
- hpa name: <source name>-source, 7 fixed chars
fixed chars length: 18, length of <function name>: 1~45

solutions:

1. limit the length of the name of Function/Sink/Source to 1~43 chars
2. limit each resource individually (1\~43 chars for Function, 1\~47 chars for Sink, and 1\~45 chars for Source)
3. do not limit the length of the name, but when it is too long, cut it off

I prefer the first or third solution, what do you think?

**Comment by jiangpengcheng** [comment]
I prefer the first or third solution too

**Comment by tpiperatgod** [comment]
I verified and found that the third solution fails when the first 43 characters of the names of some resources are the same.

So maybe we should limit resource names to a maximum of 43 characters?
