### ISSUE TITLE
Add integration tests for auth parameters

### ISSUE THREAD

**Issue by jiangpengcheng** [streamnative/function-mesh#441]
we should at least cover cases when pulsar uses oauth2(sn cloud is using this)

and add others(tls, basic auth, jwt...) when possible.

**Comment by jiangpengcheng** [comment]
@streamnative/serverless 

do you know whether is it easy to deploy pulsar with oauth2 enabled via [charts](https://github.com/streamnative/charts)? if not, how about using an existing cluster create in the [test env](https://console.test.cloud.gcp.streamnative.dev/)

**Comment by freeznet** [comment]
@jiangpengcheng could you please add the charts PR link to this issue? thanks.

**Comment by jiangpengcheng** [comment]
PR: https://github.com/streamnative/charts/pull/851 which make it's easy to deploy pulsar with oauth2 as the authentication provider
