### ISSUE TITLE
release 0.4.0 to operator-hub and openshift

### ISSUE THREAD

**Issue by freeznet** [streamnative/function-mesh#442]
- [x] operator-hub https://github.com/k8s-operatorhub/community-operators/pull/1584
- [x] openshift certificated https://github.com/redhat-openshift-ecosystem/certified-operators/pull/1105
- [ ] release process update

**Comment by hpvd** [comment]
maybe it makes sense to first close https://github.com/streamnative/function-mesh/issues/371

**Comment by freeznet** [comment]
@hpvd thanks, we will address these issues in next release, since the 0.4.0 of function-mesh is already released, this issue is only uploading the released version to different registries.

**Comment by hpvd** [comment]
@freeznet thanks for details!
