### ISSUE TITLE
Add some basic examples of using buildpacks to build function images

### ISSUE THREAD

**Issue by tpiperatgod** [streamnative/function-mesh#443]
Since we have already introduced the Buildpacks for building function images to FunctionMesh users, we need to update the website with some examples so that users can follow the guide to use this tool to simplify the process of building function images.

This issue will be used to track updates for these examples below:
- build Python function image with `.py` file
- build Java function image with `pom.xml` and `.java` file
- build Go function image with `.go` file

**Comment by hpvd** [comment]
maybe some points of this description of distroless (https://github.com/streamnative/function-mesh/issues/448) is helpful for writing the docs for building function images the common distroless route (ref https://github.com/streamnative/function-mesh/issues/418#issuecomment-1217488532) :
- advantages,
- tooling
- ...
-

**Comment by tpiperatgod** [comment]
documents are here: https://github.com/streamnative/function-mesh-website/pull/165, PTAL when you have time.

**Comment by tpiperatgod** [comment]
PR ref: https://github.com/streamnative/function-mesh-website/pull/165
