### ISSUE TITLE
Release Function Mesh 0.7.0 to openshift

### ISSUE THREAD

**Issue by freeznet** [streamnative/function-mesh#486]
- [x] k8s-operatorhub/community-operators https://github.com/k8s-operatorhub/community-operators/pull/1854
- [x] redhat-openshift-ecosystem/certified-operators https://github.com/redhat-openshift-ecosystem/certified-operators/pull/1443
- [x] redhat certificated image https://catalog.redhat.com/software/containers/62d06b34df1077330aa2619d?architecture=amd64&tag=v0.7.0

**Comment by nlu90** [comment]
👍🏼
