### ISSUE TITLE
[doc] no doc version for v0.7 on https://functionmesh.io/docs/

### ISSUE THREAD

**Issue by hpvd** [streamnative/function-mesh#498]
[doc] no doc version for v0.7 on https://functionmesh.io/docs/

- in selector latest version is v0.6
- with this no release info / no changelog page

![2022-10-28_15h23_26](https://user-images.githubusercontent.com/5681880/198616117-7dfaa4d1-d33c-4ed4-8b51-10aadd35c721.png)

![2022-10-28_15h24_18](https://user-images.githubusercontent.com/5681880/198616171-2fa315ed-d55e-4ccd-84de-88594e50e7f9.png)

**Comment by tpiperatgod** [comment]
Usually, the documentation is delayed for a while after the release, it will be available soon, please wait...

**Comment by freeznet** [comment]
close this issue since the doc is released.
