### ISSUE TITLE
[function-mesh] make run will meet two conflicting gnostic package.

### ISSUE THREAD

**Issue by imaffe** [streamnative/function-mesh#503]
When running the controller using the following command as in the `README.md`

`make generate` -> `make install` -> `make run`. The make run will throw the following panic :

![image.png](https://images.zenhubusercontent.com/61564d60ef4304714f6337a4/e175025b-8c8c-47bc-ac67-1c45e9be5495)

When using a commit before  `cf35097c653227285181d3deb9ddb998ce5706b9`   upgrade k8s dependencies to 1.22.* .

I noticed that after the above commit there are two gnosis in the go.mod file

- googleapis/gnostic
- google/gnostic.

**Comment by tpiperatgod** [comment]
You can refer to this: https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

A workaround is to change the `make run` to: 

```shell
ENABLE_WEBHOOKS=false GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn go run ./main.go
```

Of course, we'd better find a way to eradicate this problem...

**Comment by imaffe** [comment]
Thanks~ Will check out~

**Comment by imaffe** [comment]
This dep `k8s.io/kube-openapi v0.0.0-20220328201542-3ee0da9b0b42` introduced `github.com/google/gnostic@v0.5.7-v3refs` . But I couldn't find who imported `k8s.io/kube-openapi v0.0.0-20220328201542-3ee0da9b0b42`

The k8s.io/apiextensions-apiserver@v0.22.2 and `k8s.io/apimachinery@v0.24.2` introduced `k8s.io/kube-openapi@v0.0.0-20210421082810-95288971da7e` which does not refer to `github.com/google/gnostic@v0.5.7-v3refs` . So I'm thinking about changing to `	k8s.io/kube-openapi v0.0.0-20210421082810-95288971da7e // indirect`  in the go.mod. 

What I'm not sure is, the indirect `require` deps `k8s.io/kube-openapi v0.0.0-20220328201542-3ee0da9b0b42`` should come from a transitive dependency tho, but it's didn't show up in the dep graph as a transitive dep.

**Comment by imaffe** [comment]
Just learned the version here is a pseudoversion provided by the go command. Then we need to figure out why the version is introduced in the first place
