### ISSUE TITLE
[doc] The example function yaml could not be run

### ISSUE THREAD

**Issue by imaffe** [streamnative/function-mesh#504]
In the function mesh documentation, there is a step to run kubectl apply -f config/samples/compute_v1alpha1_function.yaml

And this yaml requires some extra setup, such as upload the function jar to pulsar storage or pack into the running image. The function jar location refers to a local test name as well.

One thing we can do is to create a demo image containing the basic jar and use the image in compute_v1alpha1_function.yaml.

![image.png](https://images.zenhubusercontent.com/61564d60ef4304714f6337a4/d934bd3d-685a-4c76-9d7a-1f6beba9ff72)

**Comment by imaffe** [comment]
There is a sample image folder to create images for running jars. Need to investigate if the samples are being used and updated now~

**Comment by imaffe** [comment]
Looks like the best way would be to create a public docker registry and use the docker image to run the documentation command.

**Comment by freeznet** [comment]
Another way is we change the example YAML to use a full pulsar image, like `pulsar-all`, and set the `java.jar` to `/pulsar/examples/...jar`, remove `jarLocation` as well.

**Comment by imaffe** [comment]
I encountered `mkdir: cannot create directory '/pulsar/conf/java-log/': Permission denied` when using the pulsar-all image, maybe need to run as root as well.

**Comment by tpiperatgod** [comment]
> I encountered `mkdir: cannot create directory '/pulsar/conf/java-log/': Permission denied` when using the pulsar-all image, maybe need to run as root as well.

what's the tag of the pulsar-all image you are using?

**Comment by imaffe** [comment]
@tpiperatgod 2.9.2.23
