### ISSUE TITLE
[function-mesh] nil pointer in MakeFunctionHPA() 

### ISSUE THREAD

**Issue by imaffe** [streamnative/function-mesh#505]
A nil pointer deference is thrown in 
![image.png](https://images.zenhubusercontent.com/61564d60ef4304714f6337a4/e8d4d5bc-50cd-4d6b-9dab-4f7fb90a2c20)

![image.png](https://images.zenhubusercontent.com/61564d60ef4304714f6337a4/5577b020-1fcf-45a1-a4b9-7bb91ce7a399)

The exception is thrown because function.Spec.MinReplica is null:

`2022-11-02T15:54:14.680+0800    INFO    function-resource       MinReplicas     {"pt": null}`

The spec json is
```
{
   "specs":{
      "className":"org.apache.pulsar.functions.api.examples.ExclamationFunction",
      "clusterName":"test-pulsar",
      "replicas":1,
      "maxReplicas":5,
      "input":{
         "typeClassName":"java.lang.String",
         "topics":[
            "persistent://public/default/java-function-input-topic"
         ]
      },
      "output":{
         "typeClassName":"java.lang.String",
         "topic":"persistent://public/default/java-function-output-topic"
      },
      "logTopic":"persistent://public/default/logging-function-logs",
      "resources":{
         "limits":{
            "cpu":"200m",
            "memory":"1100M"
         },
         "requests":{
            "cpu":"100m",
            "memory":"1G"
         }
      },
      "secretsMap":{
         "name":{
            "path":"test-secret",
            "key":"username"
         },
         "pwd":{
            "path":"test-secret",
            "key":"password"
         }
      },
      "volumeMounts":[
         {
            "name":"cache-volume",
            "mountPath":"/cache"
         }
      ],
      "autoAck":true,
      "forwardSourceMessageProperty":true,
      "maxPendingAsyncRequests":1000,
      "pod":{
         "labels":{
            "locaction":"mtv"
         },
         "annotations":{
            "managed-function":"true"
         },
         "volumes":[
            {
               "name":"cache-volume",
               "emptyDir":{
                  
               }
            }
         ],
         "imagePullSecrets":[
            {
               "name":"regcred"
            }
         ],
         "initContainers":[
            {
               "name":"init-function",
               "image":"busybox:1.28",
               "command":[
                  "sh",
                  "-c",
                  "echo The app is running! && sleep 30"
               ],
               "resources":{
                  
               }
            }
         ],
         "sidecars":[
            {
               "name":"sidecar-function",
               "image":"busybox:1.28",
               "command":[
                  "sh",
                  "-c",
                  "echo The app is running! && sleep 30000"
               ],
               "resources":{
                  
               }
            }
         ],
         "env":[
            {
               "name":"EXAMPLE_VARIABLE",
               "value":"exampleValue"
            }
         ]
      },
      "pulsar":{
         "pulsarConfig":"test-pulsar",
         "authSecret":"test-auth",
         "tlsSecret":"test-tls"
      },
      "java":{
         "jar":"pulsar-functions-api-examples.jar",
         "jarLocation":"public/default/nlu-test-java-function",
         "extraDependenciesDir":"random-dir/"
      }
   }
}
```

I can follow this issue to understand the HPA related code~

**Comment by imaffe** [comment]
Looks like my default webhook is not enabled.

**Comment by tpiperatgod** [comment]
Currently, this issue occurs during upgrades from older versions (without webhook) to newer versions. Therefore, it makes sense to solve this issue.

**Comment by imaffe** [comment]
This is because, when I run the operator controller locally using `make run`,seems the webhook is not created and thus the nil pointer. (If webhook enabled, the validation should guarantee that the nil pointer condition will not occur). Need to find a way to enable webhook in local run.

**Comment by imaffe** [comment]
Closing because we by default disables the webhook in local run. A way to work around is to provide the complete yaml config to avoid the nil pointer exception.

**Comment by imaffe** [comment]
Closing because we by default disables the webhook in local run. A way to work around is to provide the complete yaml config to avoid the nil pointer exception.

**Comment by imaffe** [comment]
> Currently, this issue occurs during upgrades from older versions (without webhook) to newer versions. Therefore, it makes sense to solve this issue.

Good to know this. For fixing this issue, do you mean something like check if the pointer is nil and provide a default value for it  before we process the Spec  (just like we did in the mutating webhook)? 

Or should we just simply detect the nil pointer and fail early and instruct the user to complete the Spec ?

**Comment by tpiperatgod** [comment]
> This is because, when I run the operator controller locally using `make run`,seems the webhook is not created and thus the nil pointer. (If webhook enabled, the validation should guarantee that the nil pointer condition will not occur). Need to find a way to enable webhook in local run.

It is recommended to use nocalhost to run the controller with webhook enabled, pls see: https://streamnative.slack.com/files/U03EV808CAC/F03RZTPPWE8/develop_functionmesh_with_nocalhost.mp4

**Comment by tpiperatgod** [comment]
> Good to know this. For fixing this issue, do you mean something like check if the pointer is nil and provide a default value for it before we process the Spec (just like we did in the mutating webhook)?
> 
> Or should we just simply detect the nil pointer and fail early and instruct the user to complete the Spec ?

I think the "default value" is better...

**Comment by imaffe** [comment]
Thanks, I'll try with the nocalhost~
