### ISSUE TITLE
Upgrade the capability level of Function Mesh Operator in operatorhub.io to "Full Lifecycle"

### ISSUE THREAD

**Issue by tpiperatgod** [streamnative/function-mesh#511]
Now the capability level of Function Mesh Operator in operatorhub.io is "Seamless Upgrades", see this: https://operatorhub.io/operator/function-mesh

Some references: 
- https://operatorhub.io/getting-started#How-do-I-start-writing-an-Operator?
- https://operatorhub.io/contribute#Publish-your-Operator-on-OperatorHub.io

**Comment by hpvd** [comment]
are there further manual steps required? Or will it automatic update with new information?

maybe also other metadata could be updated with the release of v0.8
like `operatorhub.io/ui-metadata-max-k8s-version: "1.21"` ?

![2022-11-17_12h43_27](https://user-images.githubusercontent.com/5681880/202439096-2fe1248d-38b2-4d94-9895-22fa62d8cc24.png)

https://operatorhub.io/operator/function-mesh
