### ISSUE TITLE
Provide the Function Mesh Operator addon for KubeVela to improve the ease of use of Function Mesh

### ISSUE THREAD

**Issue by tpiperatgod** [streamnative/function-mesh#525]
please refer to this guide: https://kubevela.io/docs/platform-engineers/addon/intro

**Comment by hpvd** [comment]
this looks really interesting!

**Comment by tpiperatgod** [comment]
here is the demo: https://github.com/tpiperatgod/kubevela-function-mesh-addon

**Comment by tpiperatgod** [comment]
action items:
- [ ] improvements the addon
- [ ] add a demo recording
- [ ] submit to the kubevela addon registry

**Comment by tpiperatgod** [comment]
I'm pushing to introduce the addon repo into StreamNative Org, and once it is successfully introduced, I’ll close the issue and track it in the corresponding repo

**Comment by tpiperatgod** [comment]
here is the repo: https://github.com/streamnative/kubevela-function-mesh-addon
