### ISSUE TITLE
release v0.8.0 to operatorhub and openshift

### ISSUE THREAD

**Issue by jiangpengcheng** [streamnative/function-mesh#526]

**Comment by freeznet** [comment]
- [x] k8s-operatorhub/community-operators https://github.com/k8s-operatorhub/community-operators/pull/1987
- [x] redhat-openshift-ecosystem/certified-operators https://github.com/redhat-openshift-ecosystem/certified-operators/pull/1571
- [x] redhat certificated image https://catalog.redhat.com/software/containers/62d06b34df1077330aa2619d?architecture=amd64&tag=v0.8.0
