### ISSUE TITLE
Test compatibility to newer Kubernetes versions

### ISSUE THREAD

**Issue by hpvd** [streamnative/function-mesh#555]
Readme shows tested compatibility of function mesh to Kubernetes, with latest Kubernetes version tested is v1.22 (from 4 August 2021)
https://github.com/streamnative/function-mesh#kubernetes-compatibility-matrix

Since there are some newer versions of Kubernetes available and **1.22 isn't even maintained anymore** (since 28 October 2022)
see e.g. https://en.wikipedia.org/wiki/Kubernetes#Release_timeline

we should update tests and compatibility matrix to newer versions of Kubernetes
(in best case, to the latest available version of Kubernetes on every release of a new version of function mesh)

Being at least on a Kubernetes version with ongoing maintenance, does make a lot of sense in the field of **security**,
while newer versions often bring new functionality needed for other parts/containers/microservices living in a Kubernetes installation beside function mesh.

-> the newer the Kubernetes version tested with function mesh, the better the security and the easier the trial/adaption/usage of function mesh...

**Comment by nlu90** [comment]
@hpvd Thank you for the suggestion.

Do you have any interest to help with this issue?
