### ISSUE TITLE
Python runner for pulsar master branch

### ISSUE THREAD

**Issue by yaalsn** [streamnative/function-mesh#565]
Currently, the `python` and `cpp` client are removed from pulsar repo, so there's no  `/pulsar/pulsar-client` dictionary in `pulsar-all` image. And for `/pulsar/bin/install-pulsar-client.sh`, it is changed by installing the python client from PyPI. For backward 2.11 and the earlier versions, we need to add `|| true` in the Dockerfile. What do you think? @freeznet @jiangpengcheng 

https://github.com/streamnative/function-mesh/blob/master/images/pulsar-functions-python-runner/Dockerfile

**Comment by freeznet** [comment]
We could conditionally COPY the `/pulsar/pulsar-client` and make backward compatibility changes. As for the `install-pulsar-client.sh`, it will only be triggered if the file exists, and I have checked the master branch, seems the file still exists and uses pip to install the python client, do we still need to add `|| true` to the `install-pulsar-client.sh`?

**Comment by freeznet** [comment]
@jiangpengcheng could you please help with this issue? thanks.

**Comment by jiangpengcheng** [comment]
looks like there is still a `/pulsar/pulsar-client` directory in pulsar's official docker image:

```
❯ docker run --rm apachepulsar/pulsar-all:2.11.0 ls /pulsar/pulsar-client
pulsar_client-2.11.0-cp38-cp38-manylinux1_x86_64.whl
```

will there be any differences in our pulsar-all images?

@yaalsn

**Comment by yaalsn** [comment]
@jiangpengcheng For master branch, there's no `/pulsar/pulsar-client` directory.

**Comment by yaalsn** [comment]
Hi @jiangpengcheng, for pulsar 3.0, there's no /pulsar/pulsar-client, I think we still need to add `|| true`
