### ISSUE TITLE
Manage builtin-connectors as CRD

### ISSUE THREAD

**Issue by alpreu** [streamnative/function-mesh#566]
We want to manage the builtin-connector metadata through a CRD that will contain `FunctionMeshConnectorDefinition`s

**Comment by freeznet** [comment]
Hi @alpreu , I have checked https://www.notion.so/streamnativeio/Design-IO-Connector-Deployment-Framework-0bb02491b6604083bedf4b09cc912e4c and got 1 question: 
Are this issue refers to the two types of CRD from the above design doc? `ClusterConnectorCatalog` (cluster level) and `ConnectorCatalog` (namespace level)?

**Comment by alpreu** [comment]
> Hi @alpreu , I have checked https://www.notion.so/streamnativeio/Design-IO-Connector-Deployment-Framework-0bb02491b6604083bedf4b09cc912e4c and got 1 question: Are this issue refers to the two types of CRD from the above design doc? `ClusterConnectorCatalog` (cluster level) and `ConnectorCatalog` (namespace level)?

Hi @freeznet, yes these are the CRDs we want to create

**Comment by freeznet** [comment]
Then I will have one following question:
- Since the function-mesh operator has managed the CRDs, will it require function-mesh operator to generate the merged ConfigMap from the CRs and provide it to broker's Pod? If so, it might be hard for function-mesh to mount the file to the pulsar broker.

**Comment by alpreu** [comment]
> Then I will have one following question:
> 
> * Since the function-mesh operator has managed the CRDs, will it require function-mesh operator to generate the merged ConfigMap from the CRs and provide it to broker's Pod? If so, it might be hard for function-mesh to mount the file to the pulsar broker.

No, we will only create the CR and let the broker read from it directly using a k8s client. This way we don't have to use the operator to mount files anymore

**Comment by alpreu** [comment]
closed in #585
