### ISSUE TITLE
Operator configuration with OLM deployment

### ISSUE THREAD

**Issue by MarkusNeuron** [streamnative/function-mesh#584]
As described, the function mesh operator can be [configured](https://functionmesh.io/docs/reference/function-mesh-config).

Since https://github.com/streamnative/function-mesh/pull/339 these configurations can be applyed in helm based deployments but not via OLM.

Is there any way to parameterize without manually patching the deployed operator "ClusterServiceVersion" on the cluster?

**Comment by jiangpengcheng** [comment]
looks like the only way to configure operator is using env: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md

I created a PR to parse env for flags
