### ISSUE TITLE
`cleanupSubscription` is not working

### ISSUE THREAD

**Issue by freeznet** [streamnative/function-mesh#594]
Pulsar Functions Worker cleans the subscription in Functions Worker, see https://github.com/apache/pulsar/blob/branch-2.10/pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionActioner.java#L326-L343

Function Mesh only passes the `cleanupSubscription` to the function details, but without function worker, the config is not working on Function Mesh cluster.

**Comment by tpiperatgod** [comment]
Dose it mean we need to add a mechanism to inform the Function Woker to exec `terminateFunction` when the user deletes functions in the Function Mesh cluster?

**Comment by freeznet** [comment]
@tpiperatgod not exactly, the better solution is to call pulsar admin apis to remove the subscription if the function is been deleted.
