### ISSUE TITLE
Upgrade to autoscaling/v2

### ISSUE THREAD

**Issue by freeznet** [streamnative/function-mesh#657]
Since k8s 1.23 `autoscaling/v2beta2` is deprecated, it will be great if function-mesh upgrades to `autoscaling/v2`

**Comment by MarkusNeuron** [comment]
Hi guys, this is the only thing blocking us from an needed cluster upgrade. This should be very easy to fix. Thanks for your consideration!

**Comment by MarkusNeuron** [comment]
Hi, just as info: We forked function mesh and did a "stupid" search and replace on "v2beta2" => "v2", rebuild and containerised the code and it works fine for us. So my comment above is still valid 😄 .

**Comment by freeznet** [comment]
hi @MarkusNeuron, your solution should be okay according to https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126.
Would you mind opening a PR for the fix? thanks.

**Comment by MarkusNeuron** [comment]
Hi @freeznet,
please have a look:
https://github.com/streamnative/function-mesh/pull/658
