### ISSUE TITLE
Use sidecar to routing pod logs to Pulsar topics

### ISSUE THREAD

**Issue by freeznet** [streamnative/function-mesh#663]
Options:

1. reuse the `logTopic` config, and add one more config `logTopicAgent` with possible options: `runtime` and `sidecar`. For `runtime`, the `logTopic` will keep the same behaviour to use the Pulsar Functions' log topic appender. For `sidecar`, will use filebeat to redirect the log into log topic.
2. add new config `filebeat: {}` to `RuntimeLogConfig` https://github.com/streamnative/function-mesh/blob/477841c2037c1dbd7612c4dfa06122e26524d1a8/api/compute/v1alpha1/common.go#L490-L494 and allow user to customize the filebeat configs individually.

**Comment by jiangpengcheng** [comment]
For the first option, the sinks&sources doesn't have a `logTopic` argument, seems we can only use option 2?
